#!/opt/bin/busybox sh
set -euo pipefail
IFS=$'\n\t'

SCRIPT="$(readlink -f "$0")"
ZAPRET_SCRIPT="$(dirname "$SCRIPT")/zapret"

start() {
	# --dpi-desync-fooling=badsum fix
	sysctl net.netfilter.nf_conntrack_checksum=0
	# -m connbytes fix
	sysctl net.netfilter.nf_conntrack_tcp_be_liberal=1

	"$ZAPRET_SCRIPT" start
}

stop() {
	"$ZAPRET_SCRIPT" stop

	sysctl net.netfilter.nf_conntrack_tcp_be_liberal=0
	sysctl net.netfilter.nf_conntrack_checksum=1
}

usage() {
	echo "Usage: $SCRIPT <start|stop|restart>" >&2
	exit 1
}

if [ "$#" -ne 1 ]; then
	usage
fi
case "$1" in
start)
	start
	;;

stop)
	stop
	;;

restart)
	stop
	start
	;;

*)
	usage
	;;
esac
